name: hemo_app
description: "Hemo Kan Bağış Platformu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  image_picker: ^1.2.1

  # --- FİREBASE & BİLDİRİM PAKETLERİ ---
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- İKON OLUŞTURUCU ---
  flutter_launcher_icons: ^0.13.1

# İKON AYARLARI
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  # ASSETS KISMINA LOGONU EKLEMEYİ UNUTMA
  assets:
    - assets/images/app_logo.png